// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv311sQ9rfhGM95W5627Mf5S3RjIuh1Dk',
    appId: '1:508053388777:web:65d6f18e2e1126f9bc9f78',
    messagingSenderId: '508053388777',
    projectId: 'dealstore-cb799',
    authDomain: 'dealstore-cb799.firebaseapp.com',
    storageBucket: 'dealstore-cb799.appspot.com',
    measurementId: 'G-GJ1FHXFKJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxOVPMIzevGWYs8MyruqBzED7SlN8kqw',
    appId: '1:508053388777:android:6f9fbb86f705bb1fbc9f78',
    messagingSenderId: '508053388777',
    projectId: 'dealstore-cb799',
    storageBucket: 'dealstore-cb799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKIX9zSi183LiEANwIPKg167QFZwJ_xM',
    appId: '1:508053388777:ios:328b465953d445b8bc9f78',
    messagingSenderId: '508053388777',
    projectId: 'dealstore-cb799',
    storageBucket: 'dealstore-cb799.appspot.com',
    iosBundleId: 'com.phinion.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKIX9zSi183LiEANwIPKg167QFZwJ_xM',
    appId: '1:508053388777:ios:f905b13c8b090d7fbc9f78',
    messagingSenderId: '508053388777',
    projectId: 'dealstore-cb799',
    storageBucket: 'dealstore-cb799.appspot.com',
    iosBundleId: 'com.phinion.ecommerceapp.RunnerTests',
  );
}
